title: '',
description: '',
descriptionHTML: '',
summary: '',
installs: '',
minInstalls: '',
maxInstalls: '',
score: '',
scoreText: '',
ratings: '',
reviews: '',
histogram: { '1': '', '2': '', '3': '', '4': '', '5': '' },
price: '',
free: '',
currency: '',
priceText: '',
offersIAP: '',
IAPRange: '',
androidVersion: '',
androidVersionText: '',
androidMaxVersion: '',
developer: '',
developerId: '',
developerEmail: '',
developerWebsite: '',
developerAddress: '',
developerLegalName: '',
developerLegalEmail: '',
developerLegalAddress: '',
developerLegalPhoneNumber: '',
privacyPolicy: '',
developerInternalID: '',
genre: '',
genreId: '',
categories: [
    { name: '', id: '' },
    { name: '', id: '' }
],
icon: '',
headerImage: '',
screenshots: [
    '',
    '',
],
video: '',
videoImage: '',
previewVideo: '',
contentRating: '',
contentRatingDescription: '',
adSupported: '',
released: '',
updated: '',
version: '',
recentChanges: '',
comments: [],
preregister: '',
earlyAccessEnabled: '',
isAvailableInPlayPass: '',
editorsChoice: '',
features: [
    {
        title: '',
        description: ''
    },
    {
        title: '',
        description: ''
    }
],
appId: '',
url: '',
isAvailableInPlayPass: ''
