/**
 * Essential search terms for sports and fitness apps - Top performing terms only
 * Reduced list for faster scraping while maintaining good coverage
 */

export const searchQueriesEssential = [
  // Core sports
  "sport",
  "sports",
  "sports app",
  "football",
  "football scores",
  "football news",
  "football app",
  "futbol",
  "soccer",
  "basketball",
  "basketball app",
  "basketball scores",
  "basketball news",
  "baseball",
  "tennis",
  "padel",
  "padel app",
  "padel news",
  "padel scores",
  "pickleball",
  "pickleball app",
  "pickleball news",
  "pickleball scores",
  "golf",
  "golf app",
  "golf scores",
  "golf news",
  "disc golf",
  "disc golf app",
  "hockey",
  "ice-hockey",
  "volleyball",
  "volleyball app",
  "volleyball scores",
  "swimming",
  "running",
  "running app",
  "cycling",
  "cycling app",
  "cycling scores",
  "mtb",    
  "boxing",
  "boxing app",
  "boxing scores",
  "rugby",
  "squash",
  "marathon",
  "skiing",
  "skiing app",
  "snowboarding",
  "skateboarding",
  "surfing",
  "table tennis",
  "badminton",
  "badminton app",
  "badminton scores",
  "ping pong",
  "cricket",
  "athletics",
  "F1",
    "motorsport",
    "motorsport app",
    "motorsport scores",
    "motorsport news",
    "racing",
    "handball",
    "bowling",
  "lacrosse",
  "fishing",
    "archery",
    "darts",
    "hunting",
    "pool",
  "snooker",
  "billiards",

   // Combat Sports
  "mma",
  "mixed martial arts",
  "judo",
  "karate",
  "taekwondo",
  "kickboxing",
  "sumo",
  "wrestling",
  "kendo",
  "kendo app",

  // Core fitness
  "fitness",
  "fitness app",
  "fitness workout",
  "workout",
  "workout app",
  "workout coach",
  "workout tracker",
  "gym",
  "gym app",
  "yoga",
  "yoga app",
  "pilates",
  "pilates app",
  "cardio",
  "cardio workout",
  "cardio app",
  "cardio training",
  "strength",
  "strength training",
  "weight loss",
  "muscle building",
  "muscle gain",
  "muscle",
  "home workout",
  "home workout app",
  "personal trainer",
  "personal trainer app",
  "fitivity",
  "fitivity app",
  "kettlebell",
  "routine",
  "training routine",
  "workout routine",
  "tracker",
  "training",
  "virtual trainer",
  "ai trainer",
  "ai trainer app",
  "artificial intelligence trainer",
  "fat loss",
  "fat loss app",
  "mobility",
  "mobility training",
  "stretching",
  "foam rolling",
  "les mills",
  "trx",
  "aerobics",
  "aerobics app",
  "virtual reality workout",
  "vr workout app",
  "augmented reality workout",
  "ar workout",
  "senior workout",
  "senior workout app",
  "kids workout",
  "pregnancy workout",

  // Health & wellness
  "health",
  "nutrition",
  "diet",
  "calories",
  "meditation",
  "sleep",
  "step counter",
  "weight tracker",

  // Popular apps/brands
  "nike",
  "adidas",
  "fitbit",
  "garmin",
  "strava",
  "myfitnesspal",
  "peloton",
  "headspace",
  "calm",

  // Outdoor activities
  "hiking",
  "walking",
  "walking app",
  "walking routine",
  "outdoor",
  "trail",
  "marathon",
  "marathon app",
  "marathon scores",
  "marathon news",
  "triathlon",

  // Team sports
  "fantasy sports",
  "sports betting",
  "sports news",
  "sports news app",
  "latest sports news",
  "sports scores",
  "nfl",
  "nba",
  "mlb",
  "premier league",
  "nhl",
  "ahl",
  "liiga",
  "esports",
  "champions league",
  "europa league",
  "conference league",
  "la liga",
  "series a",
  "bundesliga",
    "ligue 1",

];

export const TESTSearchQueries = [
    "football",
    "football app",
    "football scores",
    "basketball",
    "basketball app",
    "basketball scores",
    "basketball news"
]
